### ISSUE TITLE
OpenStreetPad Install

### ISSUE THREAD

**Issue by grant-humphries** [beelsebob/OpenStreetPad#20]
I am new to github, can someone walk me through exactly how to install this application on my iPhone?   Will it work on a device as old as the iPhone 3?

Sorry if this is not the proper venue to ask these questions, but this was the only method I came across to make contact.

Thanks in advance!

-Grant

**Comment by beelsebob** [comment]
Hi there Grant,

You need to clone the source code using git clone git://github.com/beelsebob/OpenStreetPad.git; then do the same for CoreParse.  Once you've done that, open the OpenStreetPad Xcode project and run it.

Note – you'll need your own developer license to do this on your device, otherwise you'll be restricted to just the simulator.

At some point I'll get round to making a proper application out of this and putting it in the store, but at the moment, OpenStreetPad is just a renderer, and rather incomplete (as you can see from the issue list).
