### ISSUE TITLE
add CoreParse as submodule

### ISSUE THREAD

**Issue by incanus** [beelsebob/OpenStreetPad#22]
Why not add CoreParse as a Git submodule for easier installation? It's rather complicated to get the project up & built, and you have to dig around to understand that CoreParse should go in a folder called CoreParse (exactly), etc.

**Comment by incanus** [comment]
Also, the iOSCoreParse target should be a dependent target of OpenStreetPad. Otherwise you have to build them in turn manually.

**Comment by beelsebob** [comment]
Because git submodules cause a variety of nasty problems, I did consider it.  Making the target dependant though I will do.

**Comment by beelsebob** [comment]
Wait... I just checked this, cleaned both iOS core parse, and OSP, and rebuilt – both built, it's already dependant.

**Comment by incanus** [comment]
The `OpenStreetPad` target is not dependent on `OSPParserGenerator`, meaning you have to build one, then switch and build the app. The app should be dependent so that you can just build it in one step if desired. 

On the topic of submodules, honest question (not trying to be difficult here) but what are the problems? I use it on a number of projects. The only things I've run into are: 
- The need to `git submodule update --init` or deeply clone a project in order to grab them the first time. 
- The incompatibility with `gh-pages` and submodule when hosting sites on GitHub. 

I've tried the [subtree merge solution](http://help.github.com/subtree-merge/) on [another project](https://github.com/mapbox/tilemill) in order to avoid the `gh-pages` issue, but there, one side effect is sub-project histories that predate the main project and throw off the development history timeline. But that's pretty minor. 

Anyway, just a thought. I'd be happy to contribute pull requests for both dependent target as well as submodules, unless I'm misunderstanding something.

**Comment by beelsebob** [comment]
On 29 Feb 2012, at 18:04, Justin R. Miller wrote:

> The `OpenStreetPad` target is not dependent on `OSPParserGenerator`, meaning you have to build one, then switch and build the app. The app should be dependent so that you can just build it in one step if desired. 

Ah fair point, I hadn't done that so far because the amount of time I spend rebuilding the parser archiver is tiny compared to the time it would take me to figure out how to make it a dependent target, and add a target to run the output of it to generate the archive, and then make that dependent.  I'll look into setting that up properly at some point.

> On the topic of submodules, honest question (not trying to be difficult here) but what are the problems? I use it on a number of projects. The only things I've run into are: 
> - The need to `git submodule update --init` or deeply clone a project in order to grab them the first time. 
> - The incompatibility with `gh-pages` and submodule when hosting sites on GitHub. 

These are precisely the two points I was going to bring up:
Re 1:
git clone git://github.com/beelsebob/CoreParse.git
git clone git://github.com/beelsebob/OpenStreetPad.git

is easier than:
git clone git://github.com/beelsebob/OpenStreetPad.git
cd OpenStreetPad
git submodule update --init.

Re 2:
I use gh-pages to host CoreParse's documentation, I intend to use it for OpenStreetPad when I break out the renderer into a static library.

For a bonus 3:
It's easier for me to maintain the two independently with different repo versions if they're independent of one and other.

> Anyway, just a thought. I'd be happy to contribute pull requests for both dependent target as well as submodules, unless I'm misunderstanding something.
> I'd rather you did that if possible.  I don't anticipate there being any serious problems with CoreParse in OSP – CoreParse is pretty stable now, but then I guess nothing can be ruled out.

Thanks

Tom Davie
