### ISSUE TITLE
Way names in russian are not displayed

### ISSUE THREAD

**Issue by medvedNick** [beelsebob/OpenStreetPad#35]
Description:
Russian names of roads are not showed. The problem is only with objects, which have value "line" for key "text-position" in tags. There is a message "<Error>: Helvetica-Light: FT_Load_Glyph failed: error 6" in console

Steps to reproduce:
1) replace TestData.pbf with that one: http://dl.dropbox.com/u/45754014/TestData.pbf
2) replace 71st string in OSPMapView with: [self setMapArea:OSPMapAreaMake(OSPCoordinate2DProjectLocation(CLLocationCoordinate2DMake(55.74234, 37.61374)), 17.0)];
3) build and run OpenStreetPad

Expected result:
All roads' names displayed correctly

Actual result:
Roads' names are not displayed (but buildings' names are) and console message  "<Error>: Helvetica-Light: FT_Load_Glyph failed: error 6" is showed

**Comment by beelsebob** [comment]
The issue you're hitting is basically that the russian characters don't exist in the font you're specifying in the style sheet.  The reason it works for "center" text positioned stuff is because apple's font engine is automatically falling back to an alternative font there.  A temporary fix would be to simply specify a font that includes cyrilic characters, I'll take a look at trying to get the fallback mirroring what apple does though.

**Comment by medvedNick** [comment]
yes, force assignment fontFamily = @"Arial" in code let the engine load cyrilic characters, but it contradicts mapCSS file with "font-family: Helvetica;". Nevertheless, it does not matter for me, so thanks!

**Comment by beelsebob** [comment]
You can do this more neatly by simply editing the highways.mcs file – set it to use Arial instead :)

Bob
if (*ra4 != 0xffc78948) { return false; }

**Comment by medvedNick** [comment]
ooh of course) bad habit to make changes in code
